#!/usr/bin/env python3

import os
import re
import subprocess
import textwrap
from collections import defaultdict
from datetime import datetime
import numpy as np
import pandas as pd
from numpy import savetxt
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.lines as mlines
from matplotlib.lines import Line2D
import matplotlib.patches as mpatches
from matplotlib.colors import ListedColormap, LogNorm, Normalize
import seaborn as sns

#def overlay_plots():
path = '/Users/jaredshemonsky/Downloads/INDELibleV1.03/tree_graphs/t1 (((A1:0.35,B1:0.35):0.06,C1:0.41):0.09,D1:0.5);'

image_files = []
for file in os.listdir(path):
    if file.endswith('.png'):
        file = os.path.join(path, file)
        image_files.append(file)
    else:
        print("NO PNG FILES IN FOLDER")

fig, ax = plt.subplots()

 # Loop through and overlay each image
for img_file in image_files:
    img = mpimg.imread(img_file)  # Read the image
    ax.imshow(img, alpha=0.5)  # Blend the image with alpha

    # Hide axis labels, ticks, and frame
ax.set_xticks([])
ax.set_yticks([])
ax.set_frame_on(False)
ax.axis('off')

plt.show()